- src/main/java/bean/SmemberDAO.java
- src/main/webapp/s-member/s-member_search.jsp
> 멤버찾기 검색기능 수정 (구현실패)

- src/main/java/bean/SprojectDAO.java
- src/main/java/bean/SprojectDTO.java
- src/main/webapp/s-member/s-member.jsp
- src/main/webapp/s-member/s-member_input.jsp
- src/main/webapp/s-member/s-member_inputPro.jsp
- src/main/webapp/s-project/s-project.jsp
- src/main/webapp/s-project/s-project_input.jsp
- src/main/webapp/s-project/s-project_inputPro.jsp
- src/main/webapp/style.css
멤버 등록 완성
프로젝트 등록 완성
SprojectDTO, DAO 생성
스타일 파일 경로 변경
> 1101-수정-2nd

- src/main/webapp/s-member/s-member_detail.jsp
> 메일 보내기 버튼 수정

- src/main/webapp/s-member/s-member.jsp
- src/main/webapp/s-member/s-member_delete.jsp
- src/main/webapp/s-member/s-member_detail.jsp
- src/main/webapp/s-member/s-member_search.jsp
s-member , search, detail 한글패치 (  여러개의 값 가진 게시물이랑 충돌로 주석처리상태 )
+ delete page , detail에 스크립트 추가
> s-member 한글패치

- src/main/java/bean/MakeProject_CommentDAO.java
- src/main/java/bean/MakeProject_CommentDTO.java
- src/main/webapp/makeproject/comment/SmemberDAO.java
- src/main/webapp/makeproject/comment/commentDelete.jsp
- src/main/webapp/makeproject/comment/commentPro.jsp
- src/main/webapp/makeproject/comment/commentReply.jsp
- src/main/webapp/makeproject/comment/commentUpdate.jsp
- src/main/webapp/makeproject/project_detail.jsp
- src/main/webapp/makeproject/project_list.jsp
- src/main/webapp/s-member/s-member_detail.jsp
- src/main/webapp/s-project/s-project_detail.jsp
1. makeproject_comment 테이블 명 변경(comment_smember, comment_sproject 와 통일 )
2. makeproject_commentDAO 수정
3. makeproject_comment  -> board_name 컬럼추가 
4. 댓글 작성 폼 사이즈 조정
> comment 테이블 이름 통일 / 작성폼 사이즈 조정

- src/main/webapp/makeproject/project_detail.jsp
- src/main/webapp/makeproject/project_input.jsp
> makeproject_detail 글자 폼 수정

- src/main/java/bean/CommentDAO.java
- src/main/java/bean/CommentDTO.java
- src/main/webapp/admin/admin.jsp
- src/main/webapp/admin/admin_comment.jsp
- src/main/webapp/admin/admin_commentUpdate.jsp
- src/main/webapp/admin/admin_memberKick.jsp
- src/main/webapp/s-member/s-member_detail.jsp
댓글 3개 테이블 통합을 위한 DAO,DTO 생성 (sql 상에선 추가 필요 X)
댓글 통합 + 블라인드 처리 기능 추가
멤버 탈퇴기능 추가
+s-member_detail  수정,삭제 추가
> 관리자 페이지 관련

- src/main/java/bean/MemberDAO.java
- src/main/webapp/include/header.jsp
- src/main/webapp/main/index.jsp
- src/main/webapp/s-member/s-member.jsp
- src/main/webapp/style.css
> soyoul-1117-헤더 수정 완료

- src/main/webapp/member/modify.jsp
- src/main/webapp/member/myPage.jsp
멤버등급시 멤버부터 나오게
매니저 등급시 매니저부터 선택되게 수정하였습니다.
> modify 최최종수정

- src/main/java/bean/MemberDAO.java
- src/main/webapp/include/header.jsp
> soyoul-1118-헤더수정

- src/main/webapp/include/header.jsp
> soyoul-1118-헤더수정-2

- src/main/webapp/makeproject/project_detail.jsp
- src/main/webapp/makeproject/project_list.jsp
- src/main/webapp/s-member/s-member_detail.jsp
- src/main/webapp/s-project/s-project_detail.jsp
> s-project DAO,DTO 호출 코드 삽입

- src/main/webapp/member/myPage.jsp
> myPage 오류수정

- src/main/webapp/s-project/s-project_detail.jsp
> 목록 페이지 이동 코드 수정

- src/main/webapp/admin/admin.jsp
- src/main/webapp/admin/admin_cs.jsp
- src/main/webapp/cs/csContent.jsp
전체목록 보기 / 글작성 / 답변완료시 답변진행중 아래로
> 관리자 문의사항 페이지 추가

- src/main/webapp/makeproject/email/mail.jsp
- src/main/webapp/makeproject/email/mailSend.jsp
- src/main/webapp/makeproject/project_detail.jsp
- src/main/webapp/s-member/s-member_detail.jsp
- src/main/webapp/s-project/s-project_detail.jsp
s-member_detail
s-project_detail
makeproject_detail
- 메일 보내기 버튼 수정 및 추가
- 댓글 작성 전 리스트 폼 숨기기
> detail페이지 댓글작성 전 리스트폼 숨기기 수정/ makeproject 메일보내기 추가 및 수정

- src/main/webapp/makeproject/project_search.jsp
- 등급 별 프로필 사진 변경
- 리스트 출력 사이즈 변경
- 버튼 (로그인 시 노출)
- 제목 추가
> makeproject_seach 기능, 사이즈 수정

- src/main/java/bean/CommentDAO.java
- src/main/webapp/admin/admin.jsp
> admin 페이지 인기댓글 추가

- src/main/java/bean/MakeProjectDAO.java
- src/main/webapp/makeproject/project_list.jsp
- makeprojectDAO list 메서드  생성(좋아요 많은 내림차순)
- project_list페이지 좋아요 글자 순 정렬 a태그 생성 기능 구현
> 좋아요 많은 글자 순으로 정렬

- src/main/java/bean/MemberDAO.java
- src/main/webapp/message/message.jsp
- src/main/webapp/s-member/s-member_input.jsp
- src/main/webapp/s-project/s-project_input.jsp
- src/main/webapp/s-project/s-project_search.jsp
- src/main/webapp/style.css
> soyoul-1122-코드수정-2

- src/main/java/bean/BoardDAO.java
- src/main/java/bean/BoardDTO.java
- src/main/webapp/board/board.jsp
- src/main/webapp/board/content.jsp
- src/main/webapp/board/delete.jsp
- src/main/webapp/board/edit.jsp
- src/main/webapp/board/editPro.jsp
- src/main/webapp/board/searchList.jsp
- src/main/webapp/board/write.jsp
- src/main/webapp/board/writePro.jsp
- src/main/webapp/member/pw_findPro.jsp
> 코드 정리 끝(자유게시판만)

- src/main/webapp/makeproject/project_detail.jsp
- src/main/webapp/makeproject/project_list.jsp
- src/main/webapp/s-member/s-member_detail.jsp
- src/main/webapp/s-project/s-project_detail.jsp
> s-memeber s-project 이미지 경로 수정

- src/main/java/bean/MakeProjectDTO.java
- src/main/java/bean/SmemberDAO.java
- src/main/java/bean/SmemberDTO.java
- src/main/java/bean/SprojectDAO.java
- src/main/java/bean/SprojectDTO.java
- src/main/webapp/makeproject/project_detail.jsp
- src/main/webapp/makeproject/project_list.jsp
- src/main/webapp/message/message.jsp
- src/main/webapp/message/messagePrint.jsp
- src/main/webapp/message/messageSave.jsp
- src/main/webapp/s-member/s-member_detail.jsp
- src/main/webapp/s-project/s-project_detail.jsp
- src/main/webapp/style.css
* 메세지
3개 게시판에서 사용 가능
(멤버찾기, 프로젝트 찾기, 프로젝트 만들기)
> soyoul-1122-코드수정-4

- src/main/webapp/admin/admin.jsp
- src/main/webapp/admin/admin_comment.jsp
- src/main/webapp/admin/admin_cs.jsp
- src/main/webapp/admin/admin_member.jsp
- src/main/webapp/admin/admin_notice.jsp
- src/main/webapp/admin/admin_smember.jsp
- src/main/webapp/admin/admin_sproject.jsp
- src/main/webapp/style.css
> soyoul-1122-코드수정-5

- src/main/webapp/board/board.jsp
- src/main/webapp/board/content.jsp
- src/main/webapp/style.css
> soyoul-1122-코드수정-7

- src/main/webapp/makeproject/project_detail.jsp
- src/main/webapp/makeproject/project_list.jsp
center 중복 제거
makeproject_detatail 코드 위치 수정
> center 중복 제거/ makeproject 코드 위치 수정

- src/main/java/bean/Comment_SmemberDAO.java
- src/main/java/bean/Comment_SprojectDAO.java
- src/main/java/bean/MakeProjectDAO.java
- src/main/java/bean/MakeProject_CommentDAO.java
UTF-8 설정 후,
s-memberDAO
s-projectDAO
makerpojectDAO
comment DAO  부분
주석 수정
> DAO 글자 깨짐 수정[주석수정]

- src/main/webapp/s-member/s-member_detail.jsp
- src/main/webapp/s-member/s-member_input.jsp
- src/main/webapp/style.css
> soyoul-1123-코드수정

- src/main/webapp/makeproject/project_detail.jsp
- src/main/webapp/makeproject/project_input.jsp
- src/main/webapp/makeproject/project_list.jsp
- src/main/webapp/makeproject/project_update.jsp
- src/main/webapp/style.css
> makeproject 코드 및 디자인 수정

- src/main/webapp/makeproject/project_detail.jsp
- src/main/webapp/makeproject/project_input.jsp
- src/main/webapp/makeproject/project_list.jsp
- src/main/webapp/makeproject/project_search.jsp
- src/main/webapp/makeproject/project_update.jsp
- src/main/webapp/s-member/s-member_detail.jsp
- src/main/webapp/s-project/s-project_detail.jsp
- src/main/webapp/style.css
makeproject 코드정리
s-member_detail
s-project_detail
makeproject_detail
댓글 코드, 디자인 수정
style css class 디자인 추가
> 코드정리[makeproject,s-member댓글 ,s-project댓글]

- src/main/webapp/s-member/s-member.jsp
- src/main/webapp/s-member/s-member_detail.jsp
- src/main/webapp/s-member/s-member_search.jsp
- src/main/webapp/s-project/s-project.jsp
- src/main/webapp/s-project/s-project_detail.jsp
- src/main/webapp/s-project/s-project_search.jsp
> 한글패치 오타 수정

- src/main/webapp/makeproject/project_detail.jsp
- src/main/webapp/s-project/s-project_detail.jsp
> 댓글 추천 기능 코드 수정

- src/main/webapp/makeproject/project_input.jsp
- src/main/webapp/makeproject/project_list.jsp
- src/main/webapp/makeproject/project_search.jsp
> 프로젝트만들기 → 프로젝트 의뢰

- src/main/webapp/makeproject/project_detail.jsp
- src/main/webapp/makeproject/project_list.jsp
- src/main/webapp/makeproject/project_search.jsp
- src/main/webapp/s-member/s-member_detail.jsp
- src/main/webapp/s-project/s-project_detail.jsp
- 프로젝트 의뢰 페이지 코드 정리
- s-member_detail 댓글 코드 정리
> 프로젝트 의뢰 페이지 코드 정리 / s-member_detail 댓글 코드 정리
